// app/layout.js or app/RootLayout.js (depending on your file structure)
import './globals.css';  // Import global styles (including Tailwind)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        <meta name="description" content="Parkify - Mobile Parking Web App" />
        <meta name="theme-color" content="#000000" />
        <title>Parkify Mobile App</title>
      </head>
      
      <body className="bg-gray-100 min-h-screen flex flex-col">
        {/* Main container */}
        <div className="flex-grow">
          {children}  {/* Render dynamic content here */}
        </div>
        
        {/* Optional: Mobile navigation bar */}
        <nav className="fixed bottom-0 w-full bg-white border-t border-gray-300 text-center p-2">
          <a href="/" className="inline-block mx-2 text-gray-600 hover:text-gray-900">Home</a>
          <a href="/profile" className="inline-block mx-2 text-gray-600 hover:text-gray-900">Profile</a>
          <a href="/reservations" className="inline-block mx-2 text-gray-600 hover:text-gray-900">Reservations</a>
        </nav>
      </body>
    </html>
  );
}
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900", 
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
